### ISSUE TITLE
Peer to peer review 18th November

### ISSUE THREAD

**Issue by Lockless404** [gracekabaghe/leaderboard#2]
Excellent work so far Grace! Everything seems to be working as it should.

**Comment by JEFFKAY16** [comment]
Hi @gracekabaghe, 

Below are a few ways the codebase can be improved:

- Kindly add a `README.md` file to your repo. 
- It would be nice to have this [part of your HTML code](https://github.com/gracekabaghe/leaderboard/blob/62c8392f38581c14c8e63d54e6c77554c55dda6c/src/index.html#L13-L34) wrapped in a semantic tag like `section` or `main`.
- It would equally be nice to have the [footer](https://github.com/gracekabaghe/leaderboard/blob/62c8392f38581c14c8e63d54e6c77554c55dda6c/src/index.html#L35) wrapped in a `footer` tag instead of a `div` tag. This helps in the **Search Engine Optimization** process.
- Kindly remove these [blank lines](https://github.com/gracekabaghe/leaderboard/blob/62c8392f38581c14c8e63d54e6c77554c55dda6c/src/index.html#L24-L25).
- Indentation required [here](https://github.com/gracekabaghe/leaderboard/blob/62c8392f38581c14c8e63d54e6c77554c55dda6c/src/index.html#L8-L9)
